plugins {
    id 'java'
}

group = 'com.luka5w'
version = '1.1.0'

ext.javaMainClass = group + '.' + rootProject.name + '.CrackfurtJump'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    // https://mvnrepository.com/artifact/org.jetbrains/annotations
    implementation group: 'org.jetbrains', name: 'annotations', version: '19.0.0'

}

task(main, dependsOn: 'classes', type: JavaExec) {
    group = 'run'
    mainClass = javaMainClass
    classpath = sourceSets.main.runtimeClasspath
}

task(mainDev, dependsOn: 'classes', type: JavaExec) {
    group = 'run'
    mainClass = javaMainClass
    classpath = sourceSets.main.runtimeClasspath
    args '--dev'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes "Main-Class": javaMainClass
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}